version: 2.1

jobs:
    test-module:
        docker:
        - image: cimg/go:1.22.3
        steps:
        - checkout
        - run:
            name: Install dependencies
            command: cd ./module && go mod tidy
        - run:
            name: Run the tests
            command: cd ./module && go test ./...

workflows:
  test:
    jobs:
      - test-module
